name: Expense-tracker

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build & Test Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Show repository structure
        run: ls -la

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install Backend Dependencies
        working-directory: ./backend
        run: npm install

      - name: Run Backend Tests
        working-directory: ./backend
        run: npm test --if-present

      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm install

      - name: Build React App
        working-directory: ./frontend
        run: npm run build
